export default [{
    "id": 1,
    "objects": [
        {
            "id": "qrcode",
            "selectable": false,
            "type": "image",
            "originX": "left",
            "originY": "top",
            "left": 0,
            "top": 0,
            "width": 490,
            "height": 490,
            "src": "",
            "crossOrigin": "anonymous",
        }
    ],
    "background": "#ffffff",
    "canvasWidth": 490,
    "canvasHeight": 490
}, 
{
    "id": 0,
    "objects": [
        {
            "id": "bankIcon",
            "type": "image",
            "originX": "left",
            "originY": "top",
            "left": 57,
            "top": 67,
            "scaleX": 0.4,
            "scaleY": 0.4,
            "src": "",
            "crossOrigin": "anonymous"
        },
        {
            "id": "bankName",
            "type": "i-text",
            "originX": "left",
            "originY": "top",
            "left": 420,
            "top": 130,
            "fill": "#3c454c",
            "fontFamily": "helvetica",
            "fontWeight": "",
            "fontSize": 40,
            "text": ""
        }
    ],
    "backgroundImage": {
        "type": "image",
        "width": 1367,
        "height": 1939,
        "src": "/bidv-qr/b2y.png",
    }
},
{
    "id": 2,
    "objects": [
        {
            "type": "image",
            "version": "5.2.1",
            "originX": "center",
            "originY": "top",
            "left": 286.14,
            "top": 51.73,
            "width": 720,
            "height": 1080,
            "fill": "rgb(0,0,0)",
            "stroke": null,
            "strokeWidth": 0,
            "strokeDashArray": null,
            "strokeLineCap": "butt",
            "strokeDashOffset": 0,
            "strokeLineJoin": "miter",
            "strokeUniform": false,
            "strokeMiterLimit": 4,
            "scaleX": 0.34,
            "scaleY": 0.34,
            "angle": 0.49,
            "flipX": false,
            "flipY": false,
            "opacity": 1,
            "shadow": null,
            "visible": true,
            "backgroundColor": "",
            "fillRule": "nonzero",
            "paintFirst": "fill",
            "globalCompositeOperation": "source-over",
            "skewX": 0,
            "skewY": 0,
            "cropX": 0,
            "cropY": 0,
            "src": "http://fabricjs.com/assets/pug.jpg",
            "crossOrigin": null,
            "filters": []
        },
        {
            "type": "i-text",
            "version": "5.2.1",
            "originX": "left",
            "originY": "top",
            "left": 67,
            "top": 441,
            "width": 598.13,
            "height": 202.5,
            "fill": "#3c454c",
            "stroke": null,
            "strokeWidth": 1,
            "strokeDashArray": null,
            "strokeLineCap": "butt",
            "strokeDashOffset": 0,
            "strokeLineJoin": "miter",
            "strokeUniform": false,
            "strokeMiterLimit": 4,
            "scaleX": 0.5,
            "scaleY": 0.5,
            "angle": -4,
            "flipX": false,
            "flipY": false,
            "opacity": 1,
            "shadow": null,
            "visible": true,
            "backgroundColor": "",
            "fillRule": "nonzero",
            "paintFirst": "fill",
            "globalCompositeOperation": "source-over",
            "skewX": 0,
            "skewY": 0,
            "fontFamily": "helvetica",
            "fontWeight": "",
            "fontSize": 40,
            "text": "Lorem ipsum dolor sit amet,\nconsectetur adipisicing elit,\nsed do eiusmod tempor incididunt\nut labore et dolore ma",
            "underline": false,
            "overline": false,
            "linethrough": false,
            "textAlign": "left",
            "fontStyle": "normal",
            "lineHeight": 1.16,
            "textBackgroundColor": "",
            "charSpacing": 0,
            "styles": [],
            "direction": "ltr",
            "path": null,
            "pathStartOffset": 0,
            "pathSide": "left",
            "pathAlign": "baseline"
        }
    ],
    "background": "#ffffff",
    "backgroundImage": {
        "type": "image",
        "width": 690,
        "height": 490,
        "src": "https://img.vietqr.io/image/BIDV-123-xyzWuLb.png?amount=&addInfo=&accountName=",
        "crossOrigin": "anonymous"
    },
}
]